### ISSUE TITLE
The size of sils in training

### ISSUE THREAD

**Issue by enemy1205** [ShiqiYu/OpenGait#124]
According the `datasets/Gait3D/README.md` , Data Pretreatment ，
```
python datasets/pretreatment.py --input_path 'Gait3D/2D_Silhouettes' --output_path 'Gait3D-sils-64-64-pkl'
```
I testes the gaitbase use the config `configs/gaitbase/gaitbase_da_gait3d.yaml`

However , when i debug ,i find the size of sils is 64x64 
![image](https://user-images.githubusercontent.com/30740917/230120573-bc5f82dd-e214-4585-bcb9-b0c661740f97.png)
the out after backbone is 16x16
![image](https://user-images.githubusercontent.com/30740917/230120687-82be35a5-81a8-4bbd-a886-9027e0641d59.png)
But in `OpenGait:Revisiting Gait Recognition Toward Better Practicality`
6.2 . Implementation Details
"All the source codes are based on OpenGait proposed in this work. The input resolution of all datasets is 64 × 44."
So i also review the config again , 
```
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
```
should it replace "BaseSilTransform" to "BaseSilCuttingTransform" ?
I got 64x44 when i use the "BaseSilCuttingTransform" transform.
However , i also note this in `datasets/Gait3D/README.md` :
"Note: If you use the processed pickle files directly, then the size of silhouette is 64x44, which means that the pixels on both sides of the horizontal direction can no longer be cut when transforming."
So I was very confused
