### ISSUE TITLE
About the reimplement of GaitGL on SUSTech1K

### ISSUE THREAD

**Issue by aleeyang** [ShiqiYu/OpenGait#168]
**I am try to reproduce GaitGL on SUStech. But the result is higher than the report in LidarGait**
# data
I am using the Camera-Sils_aligned (not sync)
# model
The GaitGL in OpenGait
# config
The same config with GaitGL in CASIAB in OpenGait （just change the class_num to 250）

# other
btw, I also reproduce the GaitBase on SUSTech1K, and the reproduced results are almost same to the result reported in LiDARGait
# My Question
[1] Are there some  modification of the config for reproducing the result reported in LiDARGait ?
[2] Can you provide more detail of the GaitPart GaitGL GaitSet in SUStech1K?

Thank you for your time!

**Comment by chuanfushen** [comment]
There are some modifications, such as learning rate decay, max training epochs, and channel size.

We provide config of gaitgl for SUSTech1K sils.
```
evaluator_cfg:
  enable_float16: true 
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: GaitGL_cam
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 250
  SeparateBNNecks:
    class_num: 250
    in_channels: 256
    parts_num: 64

optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 20000
    - 30000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5000
  save_name: GaitGL_cam
  sync_BN: true
  total_iter: 40000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilCuttingTransform
```

**Comment by chuanfushen** [comment]
gaitpart:

```

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: GaitPart_cam
  eval_func: evaluate_indoor_dataset #evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet

model_cfg:
  model: GaitPart
  backbone_cfg:
    in_channels: 1
    layers_cfg:
      - BC-32
      - BC-32
      - M
      - BC-64
      - BC-64
      - M
      - FC-128-3
      - FC-128-3
      - FC-256-3
      - FC-256-3
    type: Plain
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 16
  bin_num:
    - 16


optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 30000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: true #true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5000
  save_name: GaitPart_sils
  sync_BN: true
  total_iter: 40000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_skip_num: 0
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilCuttingTransform
```

**Comment by chuanfushen** [comment]
gaitset:

```

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: GaitSet_sils
  eval_func: evaluate_indoor_dataset #evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet

model_cfg:
  model: GaitSet
  in_channels:
    - 1
    - 64
    - 128
    - 256
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 62
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1


optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 30000
  scheduler: MultiStepLR
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: true #true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 5000
  save_name: GaitSet_sils
  sync_BN: true
  total_iter: 40000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilCuttingTransform
```
