### ISSUE TITLE
Concatenation error between pose and sil data using skeletongait++

### ISSUE THREAD

**Issue by nyanmn** [ShiqiYu/OpenGait#224]
## System information (version)

```
- Pytorch => 2.3.0
- Operating System / Platform => Ubuntu 22.04
- Cuda => 12.0
```
## Steps to reproduce
Heatmap creation
`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=4 datasets/pretreatment_heatmap.py --pose_data_path=data/ccpg-keypoints --save_root=data/heatmap --dataset_name=CCPG
`

Creating Symbolic Links for Heatmap and Silhouette Data
`python datasets/ln_sil_heatmap.py --heatmap_data_path=/workspace/home/user/OpenGait/data/heatmap/CCPG_sigma_8.0_/pkl --silhouette_data_path=/workspace/home/user/OpenGait/data/ccpg-keypoints --output_path=/workspace/home/user/OpenGait/data/linked_outputs`

Training SkeletonGait++
`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 opengait/main.py --cfgs ./configs/skeletongait/skeletongait++_CCPG.yaml --phase train --log_to_file`

data_config part for configuration file.
```
data_cfg:
  dataset_name: CCPG
  dataset_root: /workspace/home/user/OpenGait/data/linked_outputs
  dataset_partition: ./datasets/CCPG/CCPG.json
  num_workers: 1
  data_in_use: [True, True] # heatmap, sil
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CCPG
```
The error is 
```
File "/workspace/home/user/OpenGait/opengait/modeling/models/skeletongait++.py", line 86, in inputs_pretreament
[rank1]:     cat_data = np.concatenate([pose, sil], axis=1) # [T, 3, H, W]
[rank1]:   File "<__array_function__ internals>", line 180, in concatenate
[rank1]: ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 64 and the array at index 1 has size 17
```
Those tensors were printed out and the sizes were
```
print(pose.shape)
print(sil.shape)
(30, 2, 64, 50)
(30, 1, 17, 3)
```
## Issue submission checklist
 - [ yes] I checked the problem with documentation, FAQ, issues, and have not found solution.
